kind: Secret
apiVersion: v1
metadata:
  name: "{{ lightspeed_credential_secret_name }}"
  namespace: "{{ lightspeed_namespace }}"
type: Opaque
stringData:
  {{ lightspeed_credential_key }}: '{{ lightspeed_vault_credential.secret[lightspeed_credential_key] | to_json }}'
