---
- name: BaerMetal Server
  hosts: "baremetal-bmc"
  connection: local
  gather_facts: false

  tasks:
    - name: Power On
      community.general.redfish_command:
        password: "{{ mgmt_password }}"
        username: "{{ mgmt_user }}"
        baseuri: "{{ ansible_host }}"
        category: Systems
        command: PowerOn
        resource_id: "{{ redfish_system_id }}"

    