---
- name: Sync mgmt credentials to vault
  hosts: "baremetal-bmc"
  connection: local
  gather_facts: false

  tasks:
  - name: Store the mgmt creds in Red Hat Vault
    community.hashi_vault.vault_kv2_write:
      url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
      auth_method: approle
      role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
      secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
      ca_cert: "{{ lookup('ansible.builtin.env', 'RH_VAULT_CA_CERT_FILENAME' ) }}"
      engine_mount_point: apps

      path: "coe-lab/bm-mmgt/{{ inventory_hostname }}"
      data:
        mgmt_host: "{{ ansible_host }}"
        mgmt_protocol: "{{ mmgt_protocol | default('redfish') }}"
        redfish_system_id: "{{ redfish_system_id }}"
        mgmt_user: "{{ mgmt_user }}"
        mgmt_password: "{{ mgmt_password }}"
