---
# This playbook deploys an ushift rpm VM on OCPVirt
# It uses a well prepared template VM as base.
# See the inventory/group_vars/cluster_ushiftXXX.yaml for the config
# Example to run manually:
# ansible-playbook -e ushift_env=ushift10 200-ushift-rpm-create.yaml
- hosts: "cluster_{{ ushift_env }}"
  gather_facts: false
  tasks:
    - name: Debug information
      ansible.builtin.debug:
        msg:
          - "Run aggainst {{inventory_hostname}}, vars:"
          - " - ushift_virt_namespace: {{ ushift_virt_namespace}}"
          - " - network_ip_address: {{ network_ip_address}}"
          - " - inventory_hostname: {{inventory_hostname}}"
          - " - ushift_additional_features: {{ ushift_additional_features }}"
        verbosity: 1

    - name: Create MicroShift RPM
      tags: always
      when: ushift_install_type == "rpm"
      import_role:
        name: ushift_rpm_on_kubevirt
        tasks_from: 100-create.yml

    - name: Create MicroShift ostree
      when: ushift_install_type == "ostree"
      import_role:
        name: ushift_ostree_on_kubevirt
        tasks_from: 100-create.yml

    - name: Add to ACM Hub cluster
      when: "'manage_with_acm' in ushift_additional_features"
      tags: acm,post
      import_role:
        name: feature-manage-with-acm
        tasks_from: post-deploy.yaml
      vars:
        acm_hub_clustername: "stormshift-{{inventory_hostname}}"
        acm_hub_clusterset: "stormshift"
        acm_spoke_kubeconfig: "{{ ushift_kubeconfig }}"
        acm_spoke_api_endpoint: "https://{{ inventory_hostname }}.{{ sysctx_dns_domain}}:6443"
