---
- name: Create RHEL8 template VM
  hosts: localhost
  connection: local
#  hosts: all
#  remote_user: root
  gather_facts: no
  vars_files:
    - cfg/secrets_{{sysctx_instance_name}}.yml
    - cfg/stormshift.yml

  vars:
    engine_user: admin@internal
    engine_password: "{{secret_password}}"
    engine_url: https://{{layer2_rhev_engine_fqdn}}/ovirt-engine/api
#    insecure: false
#    engine_cafile: /etc/pki/ovirt-engine/ca.pem


  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  tasks:
  # THINK ABOUT:
# virt-customize --root-password password:xxxx -a rhel-server-7.6-x86_64-kvm.qcow2

    - name: Upload RHEL8 Base Disk Imgage
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        bootable: yes
        format: cow
        alias: rhel8disk
        state: present
        upload_image_path: /home/hailstorm/coeNfs/hailstorm/iso/rhel-8.1-x86_64-kvm.qcow2
        size: 10GiB
        storage_domain: "data"
        wait: true
      tags:
        - disk
        - template

    - name: Create Template VM for rhel8
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "template_vm_rhel8"
        cluster: Default
        memory: 1GiB
        memory_guaranteed: 1GiB
        memory_max: 4GiB
        cpu_sockets: 1
        cpu_cores: 4
        cpu_threads: 1
#        cloud_init_persist: true
        cloud_init:
          host_name: "template_vm_rhel8"
          timezone: "Europe/Berlin"
          root_password: "{{secret_password}}"
          authorized_ssh_keys: "{{ sysctx_admin_ssh_key }}"
          nic_boot_protocol: "dhcp"
          nic_on_boot: true
          nic_name: "eth0"
        operating_system: rhel_8x64
        type: server
        disks:
          - name: rhel8disk
            active: true
            bootable: true
            storage_domain: data
            interface: virtio
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        graphical_console:
            headless_mode: true
        wait: true
      tags:
        - vm_create
        - template

    - name: Wait for vm to be offline - this may take a while due to yum updates
      ovirt_vm_facts:
        auth: "{{ ovirt_auth }}"
        pattern: "name=template_vm_rhel8"
        all_content: true
        fetch_nested: true
      until: '"down" in ovirt_vms[0].status'
      retries: 180
      delay: 5
      tags:
        - template


    - name: Create Template from VM
      tags: template_create, template
      ovirt_template:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: rhel8
        vm: template_vm_rhel8
        cpu_profile: Default
        state: present
        wait: true


  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
