
# DEMO Instructions:
# Call bookinfo via CURL
#export GATEWAY_URL=$(oc -n istio-system get route istio-ingressgateway -o jsonpath='{.spec.host}')
#curl -o /dev/null -s -w "%{http_code}\n" http://$GATEWAY_URL/productpage
#while true; do curl -o /dev/null -s -w "%{http_code}\n" http://$GATEWAY_URL/productpage; done
#
# Call via Browser:
# URL: http://istio-ingressgateway-istio-system.apps.ocp3.stormshift.coe.muc.redhat.com/productpage
#
# Access Kiali:
# URL https://kiali-istio-system.apps.ocp3.stormshift.coe.muc.redhat.com/console/overview?duration=60&pi=15000

- name: Deploy Open Data Hub Operator
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - cfg/secrets.yml
    - cfg/stormshift.yml
  vars:
    odhns: "dfroehli-odh"

  tasks:
    - name: Create odh project
      tags: controlplane
      k8s:
        state: present
        definition:
          kind: Project
          apiVersion: project.openshift.io/v1
          metadata:
            name: "{{odhns}}"
            annotations:
              openshift.io/description: "OpenDataHub Example"

    - name: Add allauthenticated as project admins
      tags: controlplane
      k8s:
        state: present
        definition:
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            creationTimestamp: null
            namespace: "{{odhns}}"
            name: project-admin-binding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: "system:authenticated"

# ------------------------------------------------------
# Install Operator
    - name: Install Operator
      tags: controlplane
      register: operators
      k8s:
        state: present
        definition:
          - kind: Subscription
            apiVersion: operators.coreos.com/v1alpha1
            metadata:
              name: opendatahub-operator
              namespace: "{{odhns}}"
            spec:
              channel: alpha
              installPlanApproval: Automatic
              name: opendatahub-operator
              source: community-operators
              sourceNamespace: openshift-marketplace
              startingCSV: opendatahub-operator.v0.5.0

    - name: Wait for Operator Install to complete
      shell: sleep 5s && oc get ClusterServiceVersion -n {{odhns}} --no-headers | grep -v Succeeded | wc -l
      register: operatorsNotSucceded
      until: " '0' in operatorsNotSucceded.stdout"
      retries: 120
      changed_when: false
      when: operators is changed
