---
- hosts: cluster
  connection: local
  gather_facts: false
  serial: 1
  tasks:

    # - name: List clusters
    #   community.hashi_vault.vault_list:
    #     url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
    #     auth_method: approle
    #     role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
    #     secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
    #     validate_certs: false
    #     # engine_mount_point: apps

    #     path: "apps/metadata/coe-lab/cluster-credential"
    #   register: clusters

    # - debug: var=clusters
    - name: Get Creds
      community.hashi_vault.vault_kv2_get:
        url: "{{ lookup('ansible.builtin.env', 'RH_VAULT_URL' ) }}"
        auth_method: approle
        role_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_ROLE_ID' ) }}"
        secret_id: "{{ lookup('ansible.builtin.env', 'RH_VAULT_SECRET_ID' ) }}"
        validate_certs: false
        engine_mount_point: apps
        path: "coe-lab/cluster-credential/stormshift-{{ inventory_hostname }}"
      register: cluster  

    - name: "Show kubeadmin password"
      debug:
        msg: "Kubeadmin password is: {{ cluster.secret['kubeadmin-password'] }}"

    - name: Export kubeconfig
      copy:
        content: "{{ cluster.secret.kubeconfig }}"
        dest: "kubeconfig-stormshift-{{ inventory_hostname }}"

    - name: Export kubeadmin-password
      copy:
        content: "{{ cluster.secret['kubeadmin-password'] }}"
        dest: "kubeadmin-password-stormshift-{{ inventory_hostname }}"
    
    # https://github.com/danielfoehrKn/kubeswitch
    - name: Kubeswitch preperations
      when: kubeswitch | default('false') | bool
      block:
        - name: Rebuild new kubeconfig
          ansible.builtin.set_fact:
            kubeconfig: "{{ cluster.secret.kubeconfig | ansible.builtin.from_yaml | combine(fields_to_change, recursive=true) }}"
          vars:
            fields_to_change:
              current-context: "stormshift-{{ inventory_hostname  }}"
              contexts:
                - name: "stormshift-{{ inventory_hostname }}"
                  context: 
                    cluster: "{{ inventory_hostname }}"
                    user: "admin"

        - name: "Write kubeswitch improved kubeconfig-{{ inventory_hostname }}"
          ansible.builtin.copy:
            content: |
              {{ kubeconfig | to_nice_yaml }}
            dest: "switch-stormshift-{{ inventory_hostname }}"

        - name: Move info
          debug:
            msg:
              - "Please run:"
              - "   mv -v scrible/switch-* ~/.kube/clusters"
