---
openshift_version: 4.20.0
stormshift_owner_email: "rbohne@redhat.com"
stormshift_owner_purpose: "SSA playground"
stormshift_owner_usage: "exclusive"

cluster_type: classic
cluster_api_vip: 10.32.105.64
cluster_ingress_vip: 10.32.105.65

control_plan_cores: 8
control_plan_ram_gb: 16
control_plans:
  - vm_network_ip_address: 10.32.105.66
    vm_network_mac_address: 0E:C0:EF:20:69:42
  - vm_network_ip_address: 10.32.105.67
    vm_network_mac_address: 0E:C0:EF:20:69:43
  - vm_network_ip_address: 10.32.105.68
    vm_network_mac_address: 0E:C0:EF:20:69:44
worker_cores: 8
worker_ram_gb: 16
workers:
  - vm_network_ip_address: 10.32.105.69
    vm_network_mac_address: 0E:C0:EF:20:69:45
  - vm_network_ip_address: 10.32.105.70
    vm_network_mac_address: 0E:C0:EF:20:69:46
  - vm_network_ip_address: 10.32.105.71
    vm_network_mac_address: 0E:C0:EF:20:69:47

