---
#
# -------------------- Global hosts --------------------

coe-infrastructure:
  hosts:
    isar:

#
#
# -------------------- Template VMs --------------------
#
template_vms:
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ sysctx_dns_domain }}"
  hosts:
    rhel92-template:
      vm_cr_name: stormshift-template-rhel92
      rhel_version: "9.2"
    rhel94-template:
      vm_cr_name: stormshift-template-rhel94
      rhel_version: "9.4"
    rhel96-template:
      vm_cr_name: stormshift-template-rhel96
      rhel_version: "9.6"
    rhel10-0-template:
      vm_cr_name: stormshift-template-rhel10-0
      rhel_version: "10.0"


#
# -------------------- MICROSHIFT --------------------
#
cluster_ushift_imgbld2:
  hosts:
    ushift-imgbld2:
cluster_ushift01:
  hosts:
    ushift01:
cluster_ushift02:
  hosts:
    ushift02:
cluster_ushift03:
  hosts:
    ushift03:
cluster_ushift04:
  hosts:
    ushift04:
cluster_ushift05:
  hosts:
    ushift05:
cluster_ushift06:
  hosts:
    ushift06:
cluster_ushift07:
  hosts:
    ushift07:
cluster_ushift08:
  hosts:
    ushift08:
cluster_ushift09:
  hosts:
    ushift09:
cluster_ushift10_eus:
  hosts:
    ushift10-eus:
cluster_ushift11_ga:
  hosts:
    ushift11-ga:
cluster_ushift12_rc:
  hosts:
    ushift12-rc:
cluster_ushift13_ec:
  hosts:
    ushift13-ec:
cluster_ushift14:
  hosts:
    ushift14:
cluster_ushift15_ostree:
  hosts:
    ushift15-ostree:
cluster_ushift16_ostree:
  hosts:
    ushift16-ostree:
cluster_ushift17_ostree:
  hosts:
    ushift17-ostree:
cluster_ushift18_bootc:
  hosts:
    ushift18-bootc:
cluster_ushift19_bootc:
  hosts:
    ushift19-bootc:
cluster_ushift20:
  hosts:
    ushift20:
cluster_ushift21:
  hosts:
    ushift21-qe1:
cluster_ushift22:
  hosts:
    ushift22:

cluster_ushift_edge_fleet:
  vars:
    stormshift_owner_email: "dfroehli@redhat.com"
    stormshift_owner_purpose: "Edge Fleet Demo"
    vm_cores: 2
    vm_memory: "4Gi"
    vm_disk: "32Gi"
    # install_type - one of: rpm, ostree, imageMode
    ushift_install_type: ostree
#    ushift_uefi_boot_file: "http://ushift-imgbld.stormshift.coe.muc.redhat.com/edge-network-install/EFI/BOOT/BOOTX64.EFI"
    ushift_uefi_boot_file: "http://ushift-imgbld.stormshift.coe.muc.redhat.com/ushift-bootc-install-iso/EFI/BOOT/BOOTX64.EFI"
    ansible_host: "{{ inventory_hostname }}.{{ sysctx_dns_domain }}"
    ansible_ssh_pass: redhat02
  hosts:
    ushift-edgefleet-30:
      network_ip_address: 10.32.99.30
      network_mac_address: 0E:C0:EF:20:63:1E
    ushift-edgefleet-31:
      network_ip_address: 10.32.99.31
      network_mac_address: 0E:C0:EF:20:63:1F
    ushift-edgefleet-32:
      network_ip_address: 10.32.99.32
      network_mac_address: 0E:C0:EF:20:63:20
    ushift-edgefleet-33:
      network_ip_address: 10.32.99.33
      network_mac_address: 0E:C0:EF:20:63:21
    ushift-edgefleet-34:
      network_ip_address: 10.32.99.34
      network_mac_address: 0E:C0:EF:20:63:22
    ushift-edgefleet-35:
      network_ip_address: 10.32.99.35
      network_mac_address: 0E:C0:EF:20:63:23
    ushift-edgefleet-36:
      network_ip_address: 10.32.99.36
      network_mac_address: 0E:C0:EF:20:63:24
    ushift-edgefleet-37:
      network_ip_address: 10.32.99.37
      network_mac_address: 0E:C0:EF:20:63:25
    ushift-edgefleet-38:
      network_ip_address: 10.32.99.38
      network_mac_address: 0E:C0:EF:20:63:26
    ushift-edgefleet-39:
      network_ip_address: 10.32.99.39
      network_mac_address: 0E:C0:EF:20:63:27

ove-hackathon-mad:
  hosts:
    rdr-hub:
      # START - CUSTOM NOT IN MASTER AVAILABLE
      custom_job_name: "🇪🇸 ove-hackathon-mad rdr-hub"
      cluster_custom_namespace: ove-hackathon-mad-regional-dr
      # END - CUSTOM NOT IN MASTER AVAILABLE
      cluster_api_vip: 10.32.98.180
      cluster_ingress_vip: 10.32.98.181
      control_plans:
        - vm_network_ip_address: 10.32.98.182
          vm_network_mac_address: 0E:C0:EF:20:62:B6
        - vm_network_ip_address: 10.32.98.183
          vm_network_mac_address: 0E:C0:EF:20:62:B7
        - vm_network_ip_address: 10.32.98.184
          vm_network_mac_address: 0E:C0:EF:20:62:B8
    rdr-pri:
      # START - CUSTOM NOT IN MASTER AVAILABLE
      custom_job_name: "🇪🇸 ove-hackathon-mad rdr-hub"
      cluster_custom_namespace: ove-hackathon-mad-regional-dr
      # END - CUSTOM NOT IN MASTER AVAILABLE
      cluster_api_vip: 10.32.98.185
      cluster_ingress_vip: 10.32.98.186
      control_plans:
        - vm_network_ip_address: 10.32.98.187
          vm_network_mac_address: 0E:C0:EF:20:62:BB
        - vm_network_ip_address: 10.32.98.188
          vm_network_mac_address: 0E:C0:EF:20:62:BC
        - vm_network_ip_address: 10.32.98.189
          vm_network_mac_address: 0E:C0:EF:20:62:BD
    rdr-sec:
      # START - CUSTOM NOT IN MASTER AVAILABLE
      custom_job_name: "🇪🇸 ove-hackathon-mad rdr-hub"
      cluster_custom_namespace: ove-hackathon-mad-regional-dr
      # END - CUSTOM NOT IN MASTER AVAILABLE
      cluster_api_vip: 10.32.98.190
      cluster_ingress_vip: 10.32.98.191
      control_plans:
        - vm_network_ip_address: 10.32.98.192
          vm_network_mac_address: 0E:C0:EF:20:62:C0
        - vm_network_ip_address: 10.32.98.193
          vm_network_mac_address: 0E:C0:EF:20:62:C1
        - vm_network_ip_address: 10.32.98.194
          vm_network_mac_address: 0E:C0:EF:20:62:C2
    mdr-hub:
      # START - CUSTOM NOT IN MASTER AVAILABLE
      custom_job_name: "🇪🇸 ove-hackathon-mad mdr-hub"
      cluster_custom_namespace: ove-hackathon-mad-metro-dr
      # END - CUSTOM NOT IN MASTER AVAILABLE
      cluster_api_vip: 10.32.98.195
      cluster_ingress_vip: 10.32.98.196
      control_plans:
        - vm_network_ip_address: 10.32.98.197
          vm_network_mac_address: 0E:C0:EF:20:62:C5
        - vm_network_ip_address: 10.32.98.198
          vm_network_mac_address: 0E:C0:EF:20:62:C6
        - vm_network_ip_address: 10.32.98.199
          vm_network_mac_address: 0E:C0:EF:20:62:C7
    mdr-pri:
      # START - CUSTOM NOT IN MASTER AVAILABLE
      custom_job_name: "🇪🇸 ove-hackathon-mad mdr-hub"
      cluster_custom_namespace: ove-hackathon-mad-metro-dr
      # END - CUSTOM NOT IN MASTER AVAILABLE
      cluster_api_vip: 10.32.98.200
      cluster_ingress_vip: 10.32.98.201
      control_plans:
        - vm_network_ip_address: 10.32.98.202
          vm_network_mac_address: 0E:C0:EF:20:62:CA
        - vm_network_ip_address: 10.32.98.203
          vm_network_mac_address: 0E:C0:EF:20:62:CB
        - vm_network_ip_address: 10.32.98.204
          vm_network_mac_address: 0E:C0:EF:20:62:CC
    mdr-sec:
      # START - CUSTOM NOT IN MASTER AVAILABLE
      custom_job_name: "🇪🇸 ove-hackathon-mad mdr-hub"
      cluster_custom_namespace: ove-hackathon-mad-metro-dr
      # END - CUSTOM NOT IN MASTER AVAILABLE
      cluster_api_vip: 10.32.98.205
      cluster_ingress_vip: 10.32.98.206
      control_plans:
        - vm_network_ip_address: 10.32.98.207
          vm_network_mac_address: 0E:C0:EF:20:62:CF
        - vm_network_ip_address: 10.32.98.208
          vm_network_mac_address: 0E:C0:EF:20:62:D0
        - vm_network_ip_address: 10.32.98.209
          vm_network_mac_address: 0E:C0:EF:20:62:D1

#
# -------------------- StormShift --------------------
#
cluster:
  vars:
# Default is in roles/cluster/default/main.yaml
#    openshift_version: 4.17.0
    # cluster_base_domain is also the zone in IPA!
    cluster_base_domain: stormshift.coe.muc.redhat.com

  hosts:
    disco:  # For details have a look at host_vars/disco.yaml
    ocp1:  # For details have a look at host_vars/ocp1.yaml
    ocp2:  # For details have a look at host_vars/ocp2.yaml
    ocp3:  # For details have a look at host_vars/ocp3.yaml
    ocp6:  # For details have a look at host_vars/ocp6.yaml
    ocp7:  # For details have a look at host_vars/ocp7.yaml
    ocp8:  # For details have a look at host_vars/ocp8.yaml
    ocp9:  # For details have a look at host_vars/ocp7.yaml
    ocp11: # For details have a look at host_vars/ocp11.yaml
    ocp12: # For details have a look at host_vars/ocp11.yaml
    ocp13: # For details have a look at host_vars/ocp11.yaml
    ocp14: # For details have a look at host_vars/ocp11.yaml
