---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stormshift-automation
  namespace: stormshift-vm-templates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation
  namespace: stormshift
---
apiVersion: v1
kind: Secret
metadata:
  name: automation-token
  namespace: stormshift
  annotations:
    kubernetes.io/service-account.name: automation
  labels:
    kubernetes.io/legacy-token-last-used: '2025-12-22'
type: kubernetes.io/service-account-token
