apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: false
  namespace: netapp-trident
  imagePullPolicy: IfNotPresent
  IPv6: false
  nodePrep: 
    - iscsi
  imagePullSecrets: []
  imageRegistry: ''
  silenceAutosupport: false