---
- name: Fetch kubeconfig from vault
  ansible.builtin.include_role:
    name: internal-fetch-kubeconfig

- name: Apply ConsoleNotification
  kubernetes.core.k8s:
    kubeconfig: "{{ cluster_access_kubeconfig }}"
    state: present
    definition:
      apiVersion: console.openshift.io/v1
      kind: ConsoleNotification
      metadata:
        name: "stormshift-{{ inventory_hostname }}"
      spec:
        backgroundColor: "{{ cluster_color }}"
        color: "{{ cluster_color_fg | default('#000') }}"
        link:
          href: https://source.redhat.com/groups/public/coe-lab-munich/stormshift/stormshift_wiki/current_status_of_stormshift_clusters
          text: Details
        location: BannerTop
        text: "\U0001F32A {{ stormshift_owner_usage | capitalize }} StormShift {{ inventory_hostname }} - Managed by {{ stormshift_owner_email |default('Anonymous')}} - {{ stormshift_owner_purpose }}"
