---
- name: Include cluster_type specific tasks
  ansible.builtin.include_tasks: "post-deploy-{{ cluster_type }}.yaml"

- name: Add group local-cluster-reader
  kubernetes.core.k8s:
    kubeconfig: "{{ temp.path }}/kubeconfig"

    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: local-cluster-reader

- name: Add group local-cluster-admins
  kubernetes.core.k8s:
    kubeconfig: "{{ temp.path }}/kubeconfig"

    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: local-cluster-admins
      users: "{{
        local_cluster_admins | default([])
        + [
            tower_user_email | default('xxx') + '-admin',
            stormshift_owner_email | default('xxx') + '-admin'
        ] | reject('equalto', 'xxx-admin') }}"

- name: Add cluster role coe-cluster-admins
  kubernetes.core.k8s:
    kubeconfig: "{{ temp.path }}/kubeconfig"

    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: coe-cluster-admins
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: local-cluster-admins
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: global-cluster-admins

- name: Add cluster role coe-cluster-readers
  kubernetes.core.k8s:
    kubeconfig: "{{ temp.path }}/kubeconfig"

    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        creationTimestamp: null
        name: coe-cluster-reader
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-reader
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: local-cluster-reader
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: global-cluster-reader
